inochihautsukushii:
  id: 11
  title: 命は美しい
  members:
    third:
      - 21
      - 27
      - 9
      - 4
      - 32
      - 20
      - 6
      - 14
    second:
      - 22
      - 1
      - 3
      - 12
      - 48
    front:
      - 50
      - 13
      - 17
      - 47
      - 2
#######################################################
taiyouknock:
  id: 12
  title: 太陽ノック
  members:
    third:
      - 21
      - 11
      - 20
      - 9
      - 4
      - 5
      - 29
      - 6
    second:
      - 14
      - 22
      - 12
      - 1
      - 48
    front:
      - 13
      - 17
      - 3
      - 2
      - 47
#######################################################
ima_hanashitaidarekagairu:
  id: 13
  title: 今、話したい誰かがいる
  members:
    third:
      - 12
      - 22
      - 3
      - 21
      - 4
      - 5
    second:
      - 9
      - 14
      - 47
      - 2
      - 1
      - 20
    front:
      - 6
      - 17
      - 13
      - 48
#######################################################
harujiongasakukoroni:
  id: 14
  title: ハルジオンが咲く頃
  members:
    third:
      - 12
      - 22
      - 21
      - 3
      - 4
      - 5
      - 32
    second:
      - 9
      - 14
      - 6
      - 1
      - 20
    front:
      - 47
      - 17
      - 48
      - 13
      - 2
#######################################################
hadashidesummer:
  id: 15
  title: 裸足でSummer
  members:
    third:
      - 26
      - 20
      - 22
      - 3
      - 16
    second:
      - 14
      - 6
      - 21
      - 1
      - 12
    front:
      - 47
      - 17
      - 9
      - 13
      - 2
#######################################################
sayonaranoimi:
  id: 16
  title: サヨナラの意味
  members:
    third:
      - 16
      - 5
      - 29
      - 12
      - 3
      - 20
      - 26
      - 4
    second:
      - 22
      - 21
      - 32
      - 9
      - 6
      - 1
    front:
      - 14
      - 17
      - 47
      - 13
      - 2
#######################################################
influencer:
  id: 17
  title: インフルエンサー
  members:
    third:
      - 29
      - 5
      - 31
      - 26
      - 4
      - 20
      - 11
      - 19
      - 15
    second:
      - 22
      - 14
      - 3
      - 2
      - 21
      - 12
    front:
      - 1
      - 32
      - 17
      - 13
      - 9
      - 6
#######################################################
nigemizu:
  id: 18
  title: 逃げ水
  members:
    third:
      - 4
      - 29
      - 3
      - 12
      - 22
      - 5
    second:
      - 20
      - 21
      - 2
      - 1
      - 6
      - 14
    front:
      - 9
      - 13
      - 38
      - 46
      - 17
      - 32
